/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estruturadidaticos.interfaces;

import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.BorderFactory;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author vivi_
 */
public class FilaJFrame extends javax.swing.JFrame {
       String inserefila;
       public ArrayList<JLabel> lista;
       public ArrayList<Integer> lista2;
       int pos = 0;
       int primeiroElemento;
    
    /**
     * Creates new form FilaJFrame
     */
    public FilaJFrame() {
        lista = new ArrayList<>();
        lista2 = new ArrayList<>();
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        JanelaPrincipal = new javax.swing.JMenuItem();
        Reiniciar1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        Inserir1 = new javax.swing.JMenuItem();
        Remover = new javax.swing.JMenuItem();
        Find = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu4.setText("Menu");

        JanelaPrincipal.setText("Janela Principal");
        JanelaPrincipal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JanelaPrincipalActionPerformed(evt);
            }
        });
        jMenu4.add(JanelaPrincipal);

        Reiniciar1.setText("Reiniciar");
        Reiniciar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Reiniciar1ActionPerformed(evt);
            }
        });
        jMenu4.add(Reiniciar1);

        jMenuBar3.add(jMenu4);

        jMenu1.setText("Funções");

        Inserir1.setText("Inserir");
        Inserir1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Inserir1ActionPerformed(evt);
            }
        });
        jMenu1.add(Inserir1);

        Remover.setText("Remover");
        Remover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoverActionPerformed(evt);
            }
        });
        jMenu1.add(Remover);

        Find.setText("Procurar");
        Find.setToolTipText("");
        Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindActionPerformed(evt);
            }
        });
        jMenu1.add(Find);

        jMenuBar3.add(jMenu1);

        setJMenuBar(jMenuBar3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1325, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 721, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JanelaPrincipalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JanelaPrincipalActionPerformed
        GUI framegui = new GUI();
        framegui.setVisible(true);
        framegui.setTitle("Simulador Gráfico de Estruturas de dados");
        framegui.setLocationRelativeTo(null);
        dispose();

    }//GEN-LAST:event_JanelaPrincipalActionPerformed

    private void Reiniciar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Reiniciar1ActionPerformed
        FilaJFrame filaframe = new FilaJFrame();
        filaframe.setVisible(true);
        filaframe.setTitle("Filas");
        
        dispose();
    }//GEN-LAST:event_Reiniciar1ActionPerformed

    private void FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindActionPerformed
        if(lista2.isEmpty()){
             JOptionPane.showMessageDialog(null, "A Fila está vazia");
        }else{
             primeiroElemento = lista2.get(0);
             JOptionPane.showMessageDialog(null, "O primeiro elemento da Fila é :  " + primeiroElemento);
        }
    }//GEN-LAST:event_FindActionPerformed

    private void RemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoverActionPerformed
        if(lista2.isEmpty()){
            JOptionPane.showMessageDialog(null, "A Fila está vazia");
        }else{
            removeJlabel();
            lista2.remove(lista2.get(0));
        }
    }//GEN-LAST:event_RemoverActionPerformed

    private void Inserir1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Inserir1ActionPerformed
 
    inserefila  = JOptionPane.showInputDialog("Insira um elemento.");
    if(!isNumber(inserefila)) {
           JOptionPane.showMessageDialog(null, "Numero inválido");
    }else{
        addJlabel();
        int s = Integer.parseInt(inserefila);
        lista2.add(s);
    }
   
    }//GEN-LAST:event_Inserir1ActionPerformed
    
    
     
    private boolean isNumber(String campo){           
          return campo.matches("[0-9]+");   
    }
    public void addJlabel(){
        
        pos += 70;
        JLabel l = new JLabel("" + inserefila);
         l.setBounds(70, 70, 70, 70);
         l.setLocation(pos, 70);
        l.setBorder(BorderFactory.createLineBorder(Color.black));
        l.setFont(new Font("Trebuchet MS", Font.PLAIN, 15));
        l.setForeground(Color.BLACK);
        l.setHorizontalAlignment(SwingConstants.CENTER);
        l.setBackground(Color.GRAY);
        l.setOpaque(true);
        getContentPane().add(l);
        initComponents();
        lista.add(l);

    }
    
    private void removeJlabel(){
        lista.get(0).setVisible(false);
	lista.remove(0);
        pos -= 70;
        for(int j = 0; j < lista.size(); j++) {
            lista.get(j).setBounds(70 + (70 * j), 70, 70, 70);
           
        }	
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FilaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FilaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FilaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FilaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FilaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem Find;
    private javax.swing.JMenuItem Inserir1;
    private javax.swing.JMenuItem JanelaPrincipal;
    private javax.swing.JMenuItem Reiniciar1;
    private javax.swing.JMenuItem Remover;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar3;
    // End of variables declaration//GEN-END:variables
}
