/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estruturadidaticos.interfaces;

import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;
import javax.swing.JSlider;


public class TelaArv extends javax.swing.JDialog {

    private ArvPro arvore;
    private java.awt.Frame parent;
    public static int WINDOW_WIDTH = 800;
    public static int WINDOW_HEIGHT = 600;

    /**
     * Creates new form ABPDialog
     */
    public TelaArv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();

        this.parent = parent;
        this.setLocationRelativeTo(parent);
        this.setTitle("Árvore Binária de Pesquisa");
        this.setSize(TelaArv.WINDOW_WIDTH, TelaArv.WINDOW_HEIGHT);

        this.arvore = new ArvPro(panel);
        panel.setArvore(this.arvore);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inserirField = new javax.swing.JTextField();
        inserirLabel = new javax.swing.JLabel();
        inserirButton = new javax.swing.JButton();
        buscaLabel = new javax.swing.JLabel();
        buscaField = new javax.swing.JTextField();
        buscaButton = new javax.swing.JButton();
        panel = new estruturadidaticos.interfaces.PainelArv();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        inserirLabel.setText("Inserir Elemento");

        inserirButton.setText("Inserir Elemento");
        inserirButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inserirButtonActionPerformed(evt);
            }
        });

        buscaLabel.setText("Fazer Busca");

        buscaButton.setText("Buscar");
        buscaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscaButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(inserirLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(inserirField, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inserirButton)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(buscaLabel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(buscaField, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buscaButton)))
                .addContainerGap(247, Short.MAX_VALUE))
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirLabel)
                    .addComponent(buscaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inserirField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inserirButton)
                    .addComponent(buscaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscaButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inserirButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inserirButtonActionPerformed
        String numText = inserirField.getText();
        int num;

        try {
            num = Integer.parseInt(numText);

            if (num >= 0) {
                this.arvore.insere(num);
                this.arvore.showArvore();
                inserirField.setText("");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(panel, "Valor inválido. Digite um número", "Valor Inválido", JOptionPane.WARNING_MESSAGE);
            inserirField.setText("");
        }


    }//GEN-LAST:event_inserirButtonActionPerformed

    private void buscaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscaButtonActionPerformed

        String numText = buscaField.getText();
        int num;

        try {
            num = Integer.parseInt(numText);

            if (num >= 0) {
                ArvNo resultado = this.arvore.busca(num);
                if(resultado != null) {
                    // mostrar a mensagem
                    
                    JOptionPane.showMessageDialog(panel, "O Elemento " + num + " foi encontrado!","Valor Encontrado", JOptionPane.INFORMATION_MESSAGE);
                    buscaField.setText("");
                } else {
                    JOptionPane.showMessageDialog(panel, "Valor não encontrado", "Valor não Encontrado", JOptionPane.WARNING_MESSAGE);
                }
            }

        } catch (NumberFormatException e) {
            // MOSTRAR ERRO AQUI
            JOptionPane.showMessageDialog(panel, "Valor inválido. Digite um número", "Valor Inválido", JOptionPane.WARNING_MESSAGE);
            buscaField.setText("");
        }
    }//GEN-LAST:event_buscaButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaArv dialog = new TelaArv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscaButton;
    private javax.swing.JTextField buscaField;
    private javax.swing.JLabel buscaLabel;
    private javax.swing.JButton inserirButton;
    private javax.swing.JTextField inserirField;
    private javax.swing.JLabel inserirLabel;
    private estruturadidaticos.interfaces.PainelArv panel;
    // End of variables declaration//GEN-END:variables
}
