/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estruturadidaticos.interfaces;

import java.awt.Toolkit;

/**
 *
 * @author Viviane Cristine 
 */
public class GUI extends javax.swing.JFrame {

    /**
     * Creates new form GUI
     */
    
    public GUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        listasBotao = new javax.swing.JButton();
        pilhasBotao = new javax.swing.JButton();
        filasBotao = new javax.swing.JButton();
        arvoresBotao = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listasBotao.setText("Listas Dinâmicas");
        listasBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listasBotaoActionPerformed(evt);
            }
        });

        pilhasBotao.setText("Pilhas");
        pilhasBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pilhasBotaoActionPerformed(evt);
            }
        });

        filasBotao.setText("Filas");
        filasBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                filasBotaoActionPerformed(evt);
            }
        });

        arvoresBotao.setText("Árvores");
        arvoresBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arvoresBotaoActionPerformed(evt);
            }
        });

        jLabel1.setText("Escolha uma estrutura de dados.");

        jButton2.setText("Listas Sequenciais");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addComponent(listasBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pilhasBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(filasBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(arvoresBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 245, Short.MAX_VALUE))
                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(listasBotao)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(pilhasBotao)
                .addGap(18, 18, 18)
                .addComponent(filasBotao)
                .addGap(18, 18, 18)
                .addComponent(arvoresBotao)
                .addContainerGap(59, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /* abre janela de listas encadeadas */
    private void listasBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listasBotaoActionPerformed
        
        ListaJFrame listaframe = new ListaJFrame();
        listaframe.setVisible(true);
        listaframe.setTitle("Listas Encadeadas");
        listaframe.setLocationRelativeTo(null);
        dispose();
        
    }//GEN-LAST:event_listasBotaoActionPerformed
 /* abre uma nova janela sobre pilhas */
    private void pilhasBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pilhasBotaoActionPerformed
        PilhaJFrame pilhaframe = new PilhaJFrame();
        pilhaframe.setVisible(true);
        pilhaframe.setTitle("Pilhas");
        dispose();
    }//GEN-LAST:event_pilhasBotaoActionPerformed

    private void filasBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_filasBotaoActionPerformed
        FilaJFrame filaframe = new FilaJFrame();
        filaframe.setVisible(true);
        filaframe.setTitle("Filas");
        dispose();
    }//GEN-LAST:event_filasBotaoActionPerformed

    private void arvoresBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arvoresBotaoActionPerformed
        //ArvoreJFrame arvoreframe = new ArvoreJFrame();
        //arvoreframe.setVisible(true);
        //arvoreframe.setTitle("Árvores");
        //dispose();
        TelaArv tela = new TelaArv(this, true);
        
    }//GEN-LAST:event_arvoresBotaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        LSE lseframe = new LSE();
        lseframe.setVisible(true);
        lseframe.setTitle("Listas Sequenciais");
        
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {

               // new GUI().setVisible(true);
               GUI gui = new GUI();
               gui.setVisible(true);
               gui.setTitle("Simulador de ED");
               gui.setLocation(400, 200);
                 
               
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton arvoresBotao;
    private javax.swing.JButton filasBotao;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton listasBotao;
    private javax.swing.JButton pilhasBotao;
    // End of variables declaration//GEN-END:variables
}
