/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package estruturadidaticos.interfaces;

import java.util.ArrayList;
import javafx.scene.input.KeyCode;
import javax.swing.JOptionPane;
import javax.swing.JSlider;


public class TelaArv extends javax.swing.JDialog {
    
    String insere, remove, busca;
    private ArvPro arvore;
    private ArvBin arvore2;
    int tamArray = 0;
    int pegaNum;
    public ArrayList<Integer> buscas;
    
    private java.awt.Frame parent;
    public static int WINDOW_WIDTH = 800;
    public static int WINDOW_HEIGHT = 600;

    
    public TelaArv(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        buscas = new ArrayList<>();
        arvore2 = new ArvBin();

        initComponents();

        this.parent = parent;
        this.setLocationRelativeTo(parent);
        this.setTitle("Árvore");
        this.setSize(TelaArv.WINDOW_WIDTH, TelaArv.WINDOW_HEIGHT);

        this.arvore = new ArvPro(panel);
        panel.setArvore(this.arvore);
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new estruturadidaticos.interfaces.PainelArv();
        preOrdemButton = new javax.swing.JButton();
        posOrdemButton = new javax.swing.JButton();
        inOrdemButton = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 712, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 427, Short.MAX_VALUE)
        );

        preOrdemButton.setText("Pré-ordem");
        preOrdemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                preOrdemButtonActionPerformed(evt);
            }
        });

        posOrdemButton.setText("Pós-ordem");
        posOrdemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                posOrdemButtonActionPerformed(evt);
            }
        });

        inOrdemButton.setText("In-ordem");
        inOrdemButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inOrdemButtonActionPerformed(evt);
            }
        });

        jMenu1.setText("Menu");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Funções");
        jMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu2ActionPerformed(evt);
            }
        });

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, 0));
        jMenuItem1.setText("Inserir");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, 0));
        jMenuItem2.setText("Buscar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(preOrdemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(posOrdemButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inOrdemButton)
                .addGap(0, 457, Short.MAX_VALUE))
            .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(preOrdemButton)
                    .addComponent(posOrdemButton)
                    .addComponent(inOrdemButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void preOrdemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_preOrdemButtonActionPerformed
        arvore2.preOrdem();
    }//GEN-LAST:event_preOrdemButtonActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        String insere = JOptionPane.showInputDialog("Digite o valor: ");
        int num;

        try {
            num = Integer.parseInt(insere);

            if (num >= 0) {
                this.arvore.insere(num);
                this.arvore.showArvore();
                arvore2.inserir(num);
                buscas.add(num);
                
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(panel, "Valor inválido. Digite um número", "Valor Inválido", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    
    
    
    private void jMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenu2ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        if(buscas.isEmpty()){
            JOptionPane.showMessageDialog(null, "Árvore vazia");
        }else{    
            busca = JOptionPane.showInputDialog("Pequise um elemento.");
            if(!isNumber(busca) ) {
                JOptionPane.showMessageDialog(null, "Numero invalido");
            }
            boolean teste = pesquisa();
            if(teste == true){
                   JOptionPane.showMessageDialog(null, "Número encontrado: " + pegaNum);
            }
            if(teste == false){
                   JOptionPane.showMessageDialog(null, "Número não existe na lista");
            }
        }
        
        
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void posOrdemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_posOrdemButtonActionPerformed
        arvore2.posOrdem();
    }//GEN-LAST:event_posOrdemButtonActionPerformed

    private void inOrdemButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inOrdemButtonActionPerformed
        arvore2.inOrdem();
    }//GEN-LAST:event_inOrdemButtonActionPerformed

    public boolean pesquisa(){
        int elemento = Integer.parseInt(busca);
        
        for(int j = 0; j < buscas.size(); j++) {
                
            if(buscas.get(j) == elemento){
                
                pegaNum = buscas.get(j);
                return true;
            }
        } 
        return false;
    }
     
    private boolean isNumber(String campo){           
            return campo.matches("[0-9]+");   
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaArv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                TelaArv dialog = new TelaArv(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton inOrdemButton;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private estruturadidaticos.interfaces.PainelArv panel;
    private javax.swing.JButton posOrdemButton;
    private javax.swing.JButton preOrdemButton;
    // End of variables declaration//GEN-END:variables
}
